# Generated by Django 5.0.14 on 2025-12-04 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('order_details', models.TextField(help_text='Description of the order')),
                ('image', models.ImageField(blank=True, help_text='Optional image of the order', null=True, upload_to='orders/%Y/%m/%d/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Order price (required when delivered)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('UNDER_WORK', 'Under Work'), ('DESIGNING', 'Designing'), ('DESIGN_COMPLETED', 'Design Completed'), ('DELIVERED', 'Delivered')], default='UNDER_WORK', help_text='Current status in the workflow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Date and time when order was delivered', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'), models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['delivered_at'], name='orders_orde_deliver_1355ff_idx')],
            },
        ),
    ]
