# Generated by Django 5.0.14 on 2025-12-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shift_order_delivered_in_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNDER_WORK', 'Under Work'), ('DESIGNING', 'Designing'), ('DESIGN_COMPLETED', 'Design Completed'), ('DONE_CUTTING', 'Done Cutting'), ('DELIVERED', 'Delivered')], default='UNDER_WORK', help_text='Current status in the workflow', max_length=20),
        ),
    ]
